### ISSUE TITLE
在windows上启动redux项目报错

### ISSUE THREAD

**Issue by zhouweiming** [zhengguorong/maizuo#2]
ERROR in ./src/index.js
Module parse failed: e:\zc_test\maizuo\reduxMoonMall\src\index.js Unexpected token (16:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (16:6)
    at Parser.pp$4.raise (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExprList (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (E:\zc_test\maizuo\reduxMoonMall\node_modules\.npminstall\acorn\3.3.0\acorn\dist\acorn.js:1741:35)
 @ multi main

**Comment by zhengguorong** [comment]
我用mac没出现该错误，看你的错误信息应该是acorn这个库有问题，你试一下重新下载该依赖，或者换个版本试一下。

**Comment by zhouweiming** [comment]
mac和ubuntu不会出问题，就是在windows上出问题，这个错误只是一部分，会有一大堆warning，都是类似的，而且我把盘符改成小写（e:\...），警告会是（E:/...），盘符改成（E:/...），警告会是（e:/...）

**Comment by zhengguorong** [comment]
嗯，搞前端还是建议用mac,用win有点浪费时间，处理环境问题，心很累

**Comment by zhouweiming** [comment]
@zhengguorong 已经放弃解决了，之前是因为我的组员们是windows，所以希望能解决，最后决定全部申请mac。 因为我最后又跟踪了几天，觉得这个问题可能需要在node级别解决。最后，谢谢你的回复。

**Comment by zhengguorong** [comment]
建议用win的同学，换个ubuntu开发，也是相当不错的，当时我申请采购macbook pro，上级也是不肯的。

**Comment by zhouweiming** [comment]
ubuntu和我们目前的笔记本不兼容，还是要换笔记本，索性换mac，谢谢你的建议。
